export default {
	Function: {
		width: 158,
		height: 75,
		type: "Function",
		data: {
			label: "empty node",
			lang: "node",
			funcnode: true,
			returnArgs: [],
			loading: false,
			func: "",
			args: [],
			funcedit: true,
			argTypes: [],
			returnType: "",
			argTypeColors: [],
			hasfunc: true,
			funceval: null,
		},
		selected: false,
		dragging: false,
	},
	Bool: {
		width: 158,
		height: 75,
		type: "Bool",
		position: {
			x: 1349.3658865466373,
			y: -655.8012771633202,
		},
		data: {
			label: "bool",
			returnArgs: [],
			func: "function yorno(value) {\n\treturn value;\n} const boolval = yorno(bool); module.exports = {nodular_1699757045106: boolval };",
			funcedit: true,
			funcnode: false,
			hasfunc: true,
			defaultNode: true,
			argTypes: ["Bolean"],
			argTypeColors: [
				{
					backgroundColor: "#3380bd",
				},
			],
			args: ["bool"],
			funceval: null,
		},
		selected: false,
		dragging: false,
	},
	Input: {
		width: 158,
		height: 93,
		type: "Input",
		data: {
			label: "input",
			defaultNode: true,
			args: [],
			returnArgs: ["input"],
			funcedit: true,
			hasfunc: false,
			returnType: "String",
			returnTypeColor: {
				backgroundColor: "#A0D468",
			},
			func: "const input = `yellow`;\n\nmodule.exports = {input }",
			funceval: "yellow",
		},
		selected: false,
		dragging: false,
	},
	Array: {
		width: 158,
		height: 65,
		type: "Array",
		data: {
			label: "array",
			func: 'function array() {\n\treturn [\n\t\t"yellow",\n\t\t"blue",\n\t\t"orange",\n\t\t"red"\n\t];\n}\nmodule.exports = { array: array() }',
			args: [],
			defaultNode: true,
			returnArgs: ["array"],
			funcedit: true,
			hasfunc: true,
			returnType: "String",
			returnTypeColor: {
				backgroundColor: "#A0D468",
			},
			funceval: [],
		},
		selected: false,
		dragging: false,
	},
	Canvas: {
		width: 326,
		height: 190,
		type: "Canvas",
		data: {
			label: "canvas",
			returnArgs: ["canvas"],
			func: "const canvas = document.getElementById('nodular_1694151916161');\nconst canvas = _canvas.transferControlToOffscreen();\nmodule.exports = {canvas};",
			funcnode: false,
			canvasRef: null,
			args: [],
			funcedit: false,
			hasfunc: false,
			returnType: "",
			returnTypeColor: {
				backgroundColor: "#A0D468",
			},
			funceval: "",
		},
		selected: true,
		dragging: false,
	},
};
